version: '3.8'

services:
  nestjs-app:
    container_name: CITU-SSG-Elections-Backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

